### ISSUE TITLE
Update library to use org.json instead of javax.json

### ISSUE THREAD

**Issue by wseemann** [devilgate/pertwee#1]
Hello, I'd like to update this library to use org.json for parsing instead of javax.json since some platforms like Android don't have access to javax. Would you be willing to accept this as a hacktoberfest submission? Just wondering before I create the pull request. Thanks in advance!

**Comment by devilgate** [comment]
Sure, go ahead. It's good to know someone is even _aware_ of this!

**Comment by devilgate** [comment]
Closed by #2
