### ISSUE TITLE
Update to use Gradle, ready for publishing and create a release artifact

### ISSUE THREAD

**Issue by wseemann** [devilgate/pertwee#4]
Hello @devilgate , would you also be open to e switching this project to Gradle? If so, I can do that and also add the necessary hooks for this to be published to Maven Central (if you intend to do this). I think this is a nice project and more people would use it if I was available there. I'd also like to create a release artifact jar that you can publish here so people can use the library without having to build it themselves. Is this OK with you? It'd be similar to what I did for my own project [here](https://github.com/wseemann/Jaku).

**Comment by devilgate** [comment]
Sure, feel free. I'm glad to know somebody's using it.

**Comment by wseemann** [comment]
Hey @devilgate just following up. Does this PR work for you? Trying to get this merged before Hacktoberfest ends next week.
