### ISSUE TITLE
Support for version 1.1?

### ISSUE THREAD

**Issue by fschiettecatte** [devilgate/pertwee#7]
Hi, would it be possible to add support for [JSON Feed 1.1](https://jsonfeed.org/version/1.1)?

**Comment by devilgate** [comment]
Yes, I'd like to. Not sure I've got time at the moment, but I'll get to it when I can.

**Comment by fschiettecatte** [comment]
Do you mind my taking a shot and sending you a pull request ?

**Comment by devilgate** [comment]
Not at all, I'd be glad!

**Comment by fschiettecatte** [comment]
I created a [pull request](https://github.com/devilgate/pertwee/pull/10) for you
